import QRCode from "qrcode";
import speakeasy from "speakeasy";
import app from "../App";

/**
 * The MFA configuration response.
 */
export interface IMFAConfiguration {
  /**
   * The OTP Authentication URL
   */
  otpAuthUrl: string;
  /**
   * The Base32 code that needs to be stored next to the user.
   */
  base32: string;
}

/**
 * An advanced MFA authentication method.
 */
export class AdvancedMFA {
  /**
   * Returns an MFA Configuration.
   */
  public getMFAConfig(): IMFAConfiguration {
    const secretCode = speakeasy.generateSecret({
      name: app.app.name,
    });
    return {
      otpAuthUrl: secretCode.otpauth_url,
      base32: secretCode.base32,
    };
  }

  /**
   * Generates a QR Code for the given OTPAuth URL.
   *
   * @param otpAuthURL The OTPAuth URL we want to generate a QRCode for.
   */
  public getQRCode(otpAuthURL: string): Promise<Buffer> {
    return QRCode.toBuffer(otpAuthURL);
  }

  /**
   * Verifies a given MFA Authentication Code.
   *
   * @param authenticationCode The code generated by the Authenticator application.
   * @param userSecretMFACode The code use by the user to generate MFA codes.
   */
  public verifyAuthenticationCode(
    authenticationCode: string,
    userSecretMFACode: string
  ): boolean {
    return speakeasy.totp.verify({
      secret: userSecretMFACode,
      encoding: "base32",
      token: authenticationCode,
    });
  }
}
